# Generated by Django 4.1.2 on 2022-11-22 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temakor',
            fields=[
                ('temakor', models.CharField(blank=True, max_length=20)),
                ('tema_kulcs', models.SlugField(blank=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segedlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cim', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(blank=True, upload_to='file')),
                ('file_tipus', models.CharField(choices=[('icons/ppt.png', 'ppt'), ('icons/pdf.png', 'pdf'), ('icons/doc.png', 'doc'), ('icons/txt.png', 'txt'), ('icons/png.png', 'png'), ('icons/jpg.png', 'jpg'), ('icons/mp4.png', 'mp4'), ('icons/zip.png', 'zip')], default='ppt', max_length=13)),
                ('date', models.DateField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csapat.temakor')),
            ],
        ),
    ]
