"""
Django settings for szmcscs350 project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'AAAAB3NzaC1yc2EAAAADAQABAAABAQCsqKp+XsjM2izJedLxPYOECsKOVoGQ1v/APMumkygnga94WpnuCMWx+HV5e11GSy6gmw5PCtbpy8qF7rslehCseFDoJR0OmdWcYe+0tOmCxBe4/WnIBEJlbJEr6Ot4Xv3nVY8we+NCIuT9bUHstWa4v5EgAsiDWiNZQpufbQu5x9bTdxoePFl4upf681HhpiHxhAuVoML+A+6aA1bvrjTqs9Uei26gSOYFbTw5QIrD181kU7ATXbO3iEjICDylyYK4DHysIPp7iduuaMV5p0xqHp6FNLHFMSYCTYjble/UKgtQprkzNZPS9idr6l3fN9loEKb304JRPHmfp17QCmhT/AAAAB3NzaC1yc2EAAAADAQABAAABAQCOkLl83PBbWuWUHFSy/6l9cqfpl9hTE23CZ4shio0Ie8yTx1XYd+oMYm/UAx8q7DvDxtJSvuLpZXuIQvqp8eDoPiWIelTR4IutOhWrNmemJm8cmwoq5rEWRKNzkCe6S1xNqLCCmxqylIWMYwFYqR4QXB/e0Wx3YYcg8sSP//YMbty+TmxgRevZErkKUuYVOWQ67Ba9bGMHXpQbp9+xUBb3mjQzR8lCYgl8He8qzIbcAEDXCXoHqShIzXIPRe1xp1lQ9s6LnFge1GsBghD+Zl6chO82p1eye6OdKhQuJnG5GijajZ0H3KP1IWFcvJ4HzIFUKB3L4qPu8yloDs2Ceqvh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

PREPEND_WWW = True
BASE_URL = "https://www.szmcscs350.hu"
ALLOWED_HOSTS = ['www.szmcscs350.hu','szmcscs350.hu']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'robots',
    'imagekit',
    'captcha',

    'home',
    'galeria',
    'csapat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
     "debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SITE_ID=1

ROOT_URLCONF = 'szmcscs350.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'szmcscs350.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',

    #     'NAME': 'szmcscs350',

    #     'USER': 'szmcscs350',

    #     'PASSWORD': 'SzMCsCs350.',

    #     'HOST': 'localhost',

    #     'PORT': '5432',

    # }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL='/media/'
MEDIA_ROOT = Path(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#scurity stuff
SECURE_BROWSER_XSS_FILTER=True
SECURE_CONTENT_TYPE_NOSNIFF=True


import mimetypes

mimetypes.add_type("application/javascript", ".js", True)