# Generated by Django 4.1.2 on 2022-11-28 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('video', models.FileField(upload_to='home')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilKepek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=25)),
                ('kep', models.ImageField(blank=True, default='profilkepek/default_profile.jpg', upload_to='profilkepek/')),
            ],
        ),
        migrations.CreateModel(
            name='Tagok',
            fields=[
                ('tag_key', models.SlugField(blank=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('beosztas', models.CharField(blank=True, choices=[('1', 'csapatparancsnok'), ('2', 'csapatparancsnok helyettes'), ('3', 'rajparancsnok parancsnok'), ('4', 'segéd tiszt'), ('5', 'őrs vezető')], max_length=1)),
                ('kepesites', models.CharField(blank=True, choices=[('1', 'cst'), ('2', 'csst'), ('3', 'őv')], max_length=1)),
                ('nev', models.CharField(max_length=25)),
                ('profilkep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profilkepek')),
            ],
        ),
        migrations.CreateModel(
            name='Ors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segedorsvezeto', models.BooleanField(default=False)),
                ('orsnev', models.CharField(max_length=50)),
                ('orskep', models.ImageField(blank=True, upload_to='home/orsok/')),
                ('orsletszam', models.IntegerField()),
                ('orsvezeto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.tagok')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posztolo_neve', models.CharField(blank=True, max_length=50)),
                ('cim', models.CharField(blank=True, max_length=20)),
                ('poszt', models.TextField(blank=True)),
                ('boritokep', models.ImageField(blank=True, upload_to='blog/')),
                ('esemeny_datuma', models.DateField(blank=True)),
                ('blog_tipus', models.CharField(choices=[('be', 'beszámoló'), ('me', 'meghívó')], default='be', max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('kepek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.esemeny')),
            ],
        ),
    ]
