# Generated by Django 4.1.2 on 2022-11-28 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esemeny',
            fields=[
                ('esemeny', models.CharField(max_length=50)),
                ('esemeny_key', models.SlugField(blank=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('esemeny_date', models.IntegerField(blank=True, editable=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('temakor', models.CharField(max_length=50)),
                ('theme_key', models.SlugField(blank=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('boritokep', models.ImageField(default=0, upload_to='galleria_temakor/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='galeria/video')),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.SlugField(blank=True, editable=False)),
                ('esemeny', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='galeria.esemeny')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kepek', models.ImageField(default=0, upload_to='galeria/kepek/%Y')),
                ('date', models.DateField(auto_now_add=True)),
                ('esemeny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.esemeny')),
            ],
        ),
        migrations.AddField(
            model_name='esemeny',
            name='theme_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.theme'),
        ),
    ]
